#ifndef COMPARSION_OPERATOR_HPP
#define COMPARSION_OPERATOR_HPP

enum class ComparsionOperator {
    GREATER_THAN,
    GREATER_THAN_OR_EQUAL,
    LESS_THAN,
    LESS_THAN_OR_EQUAL,
    EQUAL,
    NOT_EQUAL
};

#endif // COMPARSION_OPERATOR_HPP
